services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - chatnet

  redis:
    image: redis:latest
    ports:
      - '6380:6379'
    networks:
      - chatnet

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge
