services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - chatnet

  redis:
    restart: always
    image: redis:latest
    networks:
      - chatnet

  nginx:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - chatnet
    ports:
      - "${EXPOSE_WEB_PORT:-8080}:8080"

networks:
  chatnet:
    driver: bridge
